[package]
name = "jinwonkim-art"
version = "0.1.0"
edition = "2021"
repository = "https://github.com/itsibitzi/jinwonkim.art"

[dependencies]
axum = { version = "0.5.6", features = ["multipart"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sqlx = { version = "0.7.4", features = ["runtime-tokio-rustls", "sqlite"] }
tera = "1.15"
thiserror = "1.0"
tokio = { version = "1.0", features = ["full"] }
tracing = "0.1.34"
tracing-subscriber = { version = "0.3.11", features = ["env-filter"] }
uuid = { version = "1.1.1", features = ["v4"] }
tower-http = { version = "0.3.0", features = ["fs", "trace"] }
anyhow = "1.0.58"
base64 = "0.13.0"
argon2 = { version = "0.4.1", features = ["std"] }
image = "0.24.5"
clap = { version = "4.4.0", features = ["derive"] }
markdown = "1.0.0-alpha.12"

# The profile that 'cargo dist' will build with
[profile.dist]
inherits = "release"
lto = "thin"

# Config for 'cargo dist'
[workspace.metadata.dist]
# The preferred cargo-dist version to use in CI (Cargo.toml SemVer syntax)
cargo-dist-version = "0.19.1"
# CI backends to support
ci = "github"
# The installers to generate for each app
installers = ["shell"]
# Target platforms to build apps for (Rust target-triple syntax)
targets = ["aarch64-apple-darwin", "x86_64-unknown-linux-gnu"]
# Path that installers should place binaries in
install-path = "CARGO_HOME"
# Publish jobs to run in CI
pr-run-mode = "plan"
# Whether to install an updater program
install-updater = false
